In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8954, 8433, 5352, 3146],
 [8954, 8433, 5352, 9932],
 [8954, 5083, 5352, 2773],
 [2751, 8417, 9242, 7048, 5067],
 [2751, 8417, 9242, 7048, 7055],
 [2980, 8954, 5422, 5352, 897],
 [1233, 6986, 8669, 7048]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8954 8433 5352 3146]
 [   0    0    0    0 8954 8433 5352 9932]
 [   0    0    0    0 8954 5083 5352 2773]
 [   0    0    0 2751 8417 9242 7048 5067]
 [   0    0    0 2751 8417 9242 7048 7055]
 [   0    0    0 2980 8954 5422 5352  897]
 [   0    0    0    0 1233 6986 8669 7048]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 79ms/step


array([[[-0.01762973,  0.03830195,  0.00207563,  0.03412041,
         -0.01840018, -0.00458514,  0.00065633, -0.04927174,
          0.025987  , -0.03225239],
        [-0.01762973,  0.03830195,  0.00207563,  0.03412041,
         -0.01840018, -0.00458514,  0.00065633, -0.04927174,
          0.025987  , -0.03225239],
        [-0.01762973,  0.03830195,  0.00207563,  0.03412041,
         -0.01840018, -0.00458514,  0.00065633, -0.04927174,
          0.025987  , -0.03225239],
        [-0.01762973,  0.03830195,  0.00207563,  0.03412041,
         -0.01840018, -0.00458514,  0.00065633, -0.04927174,
          0.025987  , -0.03225239],
        [ 0.02191595, -0.04495111, -0.03276803,  0.03389492,
          0.02967188,  0.03857424, -0.03644936, -0.02404193,
         -0.03096794,  0.04254872],
        [ 0.01609368, -0.04532752, -0.00427618,  0.00824572,
          0.04319345, -0.01413907, -0.03076006,  0.02137772,
         -0.02544138, -0.01780081],
        [ 0.04418936,  0.03747784, -0.04461384,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8954, 8433, 5352, 3146])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[-0.01762973,  0.03830195,  0.00207563,  0.03412041, -0.01840018,
        -0.00458514,  0.00065633, -0.04927174,  0.025987  , -0.03225239],
       [-0.01762973,  0.03830195,  0.00207563,  0.03412041, -0.01840018,
        -0.00458514,  0.00065633, -0.04927174,  0.025987  , -0.03225239],
       [-0.01762973,  0.03830195,  0.00207563,  0.03412041, -0.01840018,
        -0.00458514,  0.00065633, -0.04927174,  0.025987  , -0.03225239],
       [-0.01762973,  0.03830195,  0.00207563,  0.03412041, -0.01840018,
        -0.00458514,  0.00065633, -0.04927174,  0.025987  , -0.03225239],
       [ 0.02191595, -0.04495111, -0.03276803,  0.03389492,  0.02967188,
         0.03857424, -0.03644936, -0.02404193, -0.03096794,  0.04254872],
       [ 0.01609368, -0.04532752, -0.00427618,  0.00824572,  0.04319345,
        -0.01413907, -0.03076006,  0.02137772, -0.02544138, -0.01780081],
       [ 0.04418936,  0.03747784, -0.04461384,  0.03116817, -0.0471104 ,
        -0.03130523,  0.04657241, -0.02837969